### ISSUE TITLE
Can not access the bitbucket repository!

### ISSUE THREAD

**Issue by 0xE232FE** [jc01rho/ogamego_bot#2]
go: bitbucket.org/jc01rho/ogame@v0.0.0: parsing ..\ogame\go.mod: open C:\Ogame\ogame_bot\ogame\go.mod: The system cannot find the path specified.

**Comment by 0xE232FE** [comment]
ok got it. thx!

**Comment by jc01rho** [comment]
I've checked this just now. always thXfor your work @0xE232FE :)
